config/routes.rb
Rails.application.routes.draw do
  get 'home/client'
  get 'home/user'
  resources :clients
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root "home#client"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/client.rb
class Client < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: %i[ show edit update destroy ]

  # GET /clients or /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1 or /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients or /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to client_url(@client), notice: "Client was successfully created." }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1 or /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to client_url(@client), notice: "Client was successfully updated." }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1 or /clients/1.json
  def destroy
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url, notice: "Client was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:vet, :pet, :user, :home)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!


  def client
  end

  def user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/clients/_client.html.erb
<div id="<%= dom_id client %>">
  <p>
    <strong>Vet:</strong>
    <%= client.vet %>
  </p>

  <p>
    <strong>Pet:</strong>
    <%= client.pet %>
  </p>

  <p>
    <strong>User:</strong>
    <%= client.user %>
  </p>

  <p>
    <strong>Home:</strong>
    <%= client.home %>
  </p>

</div>

app/views/clients/_form.html.erb
<%= form_with(model: client) do |form| %>
  <% if client.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
        <% client.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :vet, style: "display: block" %>
    <%= form.text_field :vet %>
  </div>

  <div>
    <%= form.label :pet, style: "display: block" %>
    <%= form.text_field :pet %>
  </div>

  <div>
    <%= form.label :user, style: "display: block" %>
    <%= form.text_field :user %>
  </div>

  <div>
    <%= form.label :home, style: "display: block" %>
    <%= form.text_field :home %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing client</h1>

<%= render "form", client: @client %>

<br>

<div>
  <%= link_to "Show this client", @client %> |
  <%= link_to "Back to clients", clients_path %>
</div>

app/views/clients/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Clients</h1>

<div id="clients">
  <% @clients.each do |client| %>
    <%= render client %>
    <p>
      <%= link_to "Show this client", client %>
    </p>
  <% end %>
</div>

<%= link_to "New client", new_client_path %>

app/views/clients/new.html.erb
<h1>New client</h1>

<%= render "form", client: @client %>

<br>

<div>
  <%= link_to "Back to clients", clients_path %>
</div>

app/views/clients/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @client %>

<div>
  <%= link_to "Edit this client", edit_client_path(@client) %> |
  <%= link_to "Back to clients", clients_path %>

  <%= button_to "Destroy this client", @client, method: :delete %>
</div>

app/views/home/client.html.erb
<h1>Home#client</h1>
<p>Find me in app/views/home/client.html.erb</p>

app/views/home/user.html.erb
<h1>Home#user</h1>
<p>Find me in app/views/home/user.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reto1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <p class= "notice"> <%= notice %></p>
    <p class= "alert"><%= alert%></p>
    <%= button_to "logout", destroy_user_session_path, method: :delete  %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>